1. Numpy 를 사용할 수 있는 명령어를 적으세요

In [1]:
import numpy as np

2. 아래 내용이 나오도록 나오도록 코딩하세요

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. 아래 내용이 나오도록 코딩하세요

In [2]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. 아래 내용이 나오도록 코딩하세요

In [15]:
np.ones(10) * 5
# 변수명 [:] = 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. 아래 내용이 나오도록 코딩하세요

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. 아래 내용이 나오도록 코딩하세요

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. 아래 내용이 나오도록 코딩하세요

In [26]:
my_matrix = [[0,1,2],[3,4,5],[6,7,8]]
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. 아래 내용이 나오도록 코딩하세요.

In [27]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. 0에서 1까지의 숫자 중 랜덤 유리수가 발생되도록 코딩하세요.

In [17]:
np.random.rand(1)

array([0.09479048])

10. 표준정규분포의 의미를 쓰고, 25개의 유리수로 표현될 수 있도록 코딩하세요

In [16]:
np.random.randn(25)

array([ 0.91693956,  1.40876361,  0.87723621,  2.43506211, -1.47023297,
       -1.12791955,  0.68300443, -0.06974052,  0.03420906, -0.40513804,
       -0.05192048,  0.14667959, -0.62382069,  0.36493355, -0.4423387 ,
        1.41669535, -0.01536154,  1.07547823,  2.10746013,  0.15359574,
       -1.6107495 ,  0.21034039,  1.25660485, -1.74432125, -0.76987073])

11. 아래와 같은 내용이 나오도록 코딩하세요.

In [110]:
a=np.arange(0.01,1.01,0.01)
a

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

12. 아래와 같은 내용이 나오도록 코딩하세요

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

13. 아래와 같은 내용이 나오도록 코딩하세요

In [10]:
mat = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

14. 위 mat이라는 변수를 사용하여 아래 내용이 나오도록 코딩하세요.

In [75]:
np.array(mat)[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

15. 위 mat이라는 변수를 사용하여 아래 내용이 나오도록 코딩하세요

In [73]:
mat[3,4]

20

16.위 mat이라는 변수를 사용하여 아래 내용이 나오도록 코딩하세요.

In [78]:
mat[0:,:2][:3,1:]

array([[ 2],
       [ 7],
       [12]])

17. 위 mat이라는 변수를 사용하여 아래 내용이 나오도록 코딩하세요

In [80]:
mat[4]

array([21, 22, 23, 24, 25])

18. 위 mat이라는 변수를 사용하여 아래 내용이 나오도록 코딩하세요

In [82]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

19. 위 mat이라는 변수를 사용하여 아래 내용이 나오도록 코딩하세요.

In [11]:
mat

AttributeError: 'numpy.ndarray' object has no attribute 'plus'